name: Hello Converteo
on:
  push:
    branches:
      - main

jobs:
  hello-converteo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, Converteo!"
